### ISSUE TITLE
[3주차 과제 요구사항] 두번째 요구사항에 대해 궁금한 사항이 있습니다.

### ISSUE THREAD

**Issue by bbubbush** [bakery-blueprint/baguette-testcode#10]
#### 2. 포인트로 구매 가능한 상품 목록이 10개 이상인지 조회하는 chkPrdListInfo 메서드를 만든다.

위 요구사항이 어떤 의미인지 확인 부탁드립니다.
1. 상품 전체 목록 중 포인트로 구매 가능한 상품이 10개 이상인지 확인한다.(회원이 보유한 포인트 1000점, 상품들 중 가격이 1000원 이하인 상품이 10개)

2. 회원이 가진 포인트로 상품을 하나씩 차감 했더니 10개를 살 수 있다.(ex. 100원짜리 상품을 10개 구매 등)

**Comment by mike6321** [comment]
제가 내린 요구사항은 아니지만 저는 1번으로 생각했습니다.

**Comment by bbubbush** [comment]
넵 저도 그럼 1번으로 가정하고 진행해야겠네요  : )

감사합니다.
